name: pushCI

env:
  GO_VERSION: "1.18"
  MIN_SUPPORTED_GO_VERSION: "1.15"

on:
  push:
    branches:
      - binary-check

jobs:
  binaries:
      name: Build binaries and notarize sources
      runs-on: ubuntu-latest
      env:
        JOB_NAME: ${{ github.job }}
        JOB_ID: ${{ github.run_id }}
      outputs:
        matrix: ${{ steps.list-binaries.outputs.matrix }}
      steps:
        - uses: actions/setup-go@v3
          with:
            go-version: ${{ env.GO_VERSION }}
        - uses: actions/checkout@v3
        - name: Build binaries
          run: WEBCONSOLE=default make dist
        - id: list-binaries
          run: |
            ls -lah dist/
